name: "REI3-TICKETS-MCP-SERVER-DEV"

services:
  r3_db:
    container_name: r${R3_VERSION:-3.11.6}_db
    environment:
      POSTGRES_DB: ${R3_DB_NAME:-app}
      POSTGRES_USER: ${R3_DB_USER:-app}
      POSTGRES_PASSWORD: ${R3_DB_PASS:-app}
    image: postgres:16
    restart: always
    volumes:
      - data_db:/var/lib/postgresql/data

  r3:
    build:
      context: .
      dockerfile: rei3.Dockerfile
      args:
        r3_version: ${R3_VERSION:-3.11.6}
        r3_db_host: r3_db
        r3_db_name: ${R3_DB_NAME:-app}
        r3_db_user: ${R3_DB_USER:-app}
        r3_db_pass: ${R3_DB_PASS:-app}
        r3_os_arch: x64
        im_policy: /etc/ImageMagick-6/policy.xml
    container_name: r${R3_VERSION:-3.11.6}_app
    image: r3:${R3_VERSION:-3.11.6}
    depends_on:
      - r3_db
    ports:
      - "14000:80"
    pull_policy: never
    restart: always
    volumes:
      - data_app:/opt/r3/data

  rei3-tickets-mcp:
    build:
      context: .
      dockerfile: mcp.Dockerfile
    volumes:
      - tickets_mcp_data:/app
    network_mode: host

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    command:
      - start-dev
    volumes:
      - keycloak_data:/opt/keycloak/data
    ports:
      - "8080:8080"

volumes:
  keycloak_data:
  tickets_mcp_data:
  data_db:
  data_app: